# Ampush
# config.yml
# r evision - 0.0.1

version: 2
jobs:
  build:
    branches:
      only:
        - test_branch


    machine:
      image: circleci/classic:latest

    steps:
      - checkout

      - run:
          name: Install all Application
          command: bash ~/project/circleci_test.sh
          no_output_timeout: 1000

      - run:
          name: Run Behave code
          command: bash ~/project/run_test.sh
          no_output_timeout: 1000

      - run:
          name: Run post tests
          command: bash ~/project/post_test.sh
          no_output_timeout: 1000

          
